### ISSUE TITLE
Paper ID 2758

### ISSUE THREAD

**Issue by xuhangc** [DmitryRyumin/ICCV-2023-Papers#1]
Low-Level and Physics-based Vision section

[High-Resolution Document Shadow Removal via A Large-Scale Real-World Dataset and A Frequency-Aware Shadow Erasing Net.](https://arxiv.org/abs/2308.14221)

Repo: https://github.com/CXH-Research/DocShadow-SD7K

Page: https://cxh-research.github.io/DocShadow-SD7K/

**Comment by DmitryRyumin** [comment]
Hi @xuhangc, 👋

Thank you for providing this information.

The article, along with all additional information, has been successfully added. If you wish to make any changes, please feel free to submit modifications or additions via a pull request, as outlined in the [contributions section](https://github.com/DmitryRyumin/ICCV-2023-Papers#contributors).
