### ISSUE TITLE
Adding LiveHand paper

### ISSUE THREAD

**Issue by amundra15** [DmitryRyumin/ICCV-2023-Papers#11]
Hi, 

Could you please add our paper?

Title: LiveHand: Real-time and Photorealistic Neural Hand Rendering

Project page: https://vcai.mpi-inf.mpg.de/projects/LiveHand/

Arxiv: https://arxiv.org/abs/2302.07672

Code: https://github.com/amundra15/livehand

ICCV2023 program areas: 3D from multi-view and sensors; secondary: Image and video synthesis, Neural generative models, Vision and graphics

Thanks

**Comment by DmitryRyumin** [comment]
Hi @amundra15,

Thank you for providing the information. I have successfully added the details of your paper, including the links you provided. Additionally, I have included a link to the official PDF already published on OpenAccess.thecvf. Your help is sincerely appreciated.
