### ISSUE TITLE
Request to add our code to repository

### ISSUE THREAD

**Issue by zhiweichen0012** [DmitryRyumin/ICCV-2023-Papers#23]
Thanks for the great repository! 

We've released code for "Category-Aware Allocation Transformer for Weakly Supervised Object Localization" (Recognition: Detection). Please consider adding our repo: https://github.com/zhiweichen0012/CATR.

**Comment by DmitryRyumin** [comment]
Hi @zhiweichen0012,

Repository added successfully. Thanks for sharing!
