### ISSUE TITLE
Please add our paper

### ISSUE THREAD

**Issue by yossilevii100** [DmitryRyumin/ICCV-2023-Papers#25]
Hi,
Paper in ICCV repo: https://openaccess.thecvf.com/content/ICCV2023/html/Levi_EPiC_Ensemble_of_Partial_Point_Clouds_for_Robust_Classification_ICCV_2023_paper.html

Github page: https://github.com/yossilevii100/EPiC

YouTube video: https://m.youtube.com/watch?v=mdULLmWhotw&t=15s&pp=ygUlZXBpYyBlbnNlbWJsZSBvZiBwYXJ0aWFsIHBvaW50IGNsb3Vkcw%3D%3D

Thank you very much

**Comment by DmitryRyumin** [comment]
Hi @yossilevii100,

Thanks for letting me know. I've checked the links provided, and it seems that all the links except for the YouTube video were already added previously. I have now added the YouTube video link to the repo. You can find the updated version in the section [here](https://github.com/DmitryRyumin/ICCV-2023-Papers/blob/main/sections/2023/main/3d-shape-modeling-and-processing.md). Also, all information has been synchronized with the [Hugging Face app](https://huggingface.co/spaces/DmitryRyumin/NewEraAI-Papers).

<img width="700" alt="Hugging Face app" src="https://github.com/DmitryRyumin/ICCV-2023-Papers/assets/34124149/53abc938-ac6f-4fbd-b673-0b9be688b9ee">
