### ISSUE TITLE
Please add our project page

### ISSUE THREAD

**Issue by shortcut-v2v** [DmitryRyumin/ICCV-2023-Papers#7]
I appreciate for your awesome repository!

I checked my work, "Shortcut-V2V: Compression Framework for Video-to-Video Translation based on Temporal Redundancy Reduction", had been added on the table.

However, I just want you to add our project website [https://shortcut-v2v.github.io/](https://shortcut-v2v.github.io/)!

Thank you in advance!

**Comment by DmitryRyumin** [comment]
Hi @shortcut-v2v, 👋

The link to the GitHub page has been successfully added. You can now find it in the appropriate section.

If you have any other requests or need further assistance, please let me know.
